version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cloud
      MYSQL_DATABASE: cloud
      MYSQL_USER: cloud
      MYSQL_PASSWORD: cloud
#    networks:
#      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    volumes:
      - pma_vol:/home/ubuntu/pma
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: cloud
      PMA_ABSOLUTE_URI: http://example.com/pma/
#    networks:
#      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: cloud
      WORDPRESS_DB_PASSWORD: cloud
      WORDPRESS_DB_NAME: cloud
#    networks:
#      - wpsite
  proxy:
    depends_on:
#      - wordpress
      - phpmyadmin
    image: nginx:1.23
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
#    networks:
#      - wpsite
#networks:
#  wpsite:
volumes:
  db_data:
  pma_vol:
