version: '3'
services:
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql_server
    image: phpmyadmin/phpmyadmin
    volumes:
      - pma_vol:/home/ubuntu/pma
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      PMA_ABSOLUTE_URI: http://example.com/pma/

  mysql_server:
    container_name: mysql_server
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  wordpress:
    container_name: wordpress_app
    depends_on:
      - mysql_server
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}

  proxy:
    container_name: nginx-proxy
    depends_on:
      - phpmyadmin
    image: nginx:1.23
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
  pma_vol:
