version: '3'
services:

  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:latest
    container_name: wp-wordpress
    env_file:
      - .env
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - database
    volumes: ['./:/var/www/html']
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}

  database:
    # default port 3306
    image: mysql:5.7
    container_name: wp-database
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MY SQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.23
    container_name: wp-nginx
    env_file:
      - .env
    restart: always
    depends_on:
      - phpmyadmin
    ports:
      - "80:80"    # http
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    volumes:
      - pma_vol:/home/ubuntu/pma
    restart: always
    ports:
      - '3306:80' #port default to public
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      PMA_ABSOLUTE_URI: http://example.com/pma/


volumes:
  db_data:
  pma_vol:

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge
