version: '3'
services:

  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:latest
    container_name: wp-wordpress
    env_file:
      - .env
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - db
    volumes: ['./:/var/www/html']
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}

  db:
    image : mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      TERM: xterm
      APP_ENV: dev
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
    container_name: mysql


  proxy:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.23
    env_file:
      - .env
    restart: always
    ports:
      - "80:80"    # http
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    volumes:
      - pma_vol:/home/ec2-user/pma
    restart: always
    ports:
      - '8001:80' #port default to public
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}


volumes:
  db_data:
  pma_vol:
